Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "site.yml"
    ansible.limit = "all"
    ansible.inventory_path = "local"
    ansible.raw_arguments = "--connection=local"
  end
end
